version: '3.4'

services:
  coreapp.api:
    image: coreappapi:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_coreapp.api$
    volumes:
      - C:\Users\Mohsen\Desktop\tst\CoreApp\CoreApp.Api:/app
      - C:\Users\Mohsen\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_coreapp.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_coreapp.api$ bin/Debug/netcoreapp2.0/CoreApp.Api.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
